# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yuniq's Tech Blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my tech blog, I occasionally will post here
  about different things that I am working on, and even
  sometimes just be sharing something I might find interesting.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yuniq.tech" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  yuniq-neko
instagram_username: speshialy
linkedin_username: caleb-fraser-b2936116a
rss: feed.xml

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
